---
- hosts: webservers
  become: true
  vars:
   ansible_become_pass: edureka
  tasks:
  - name: Install Git
    package:
     name: git
     state: present

  - name: Run update
    apt:
     update_cache: true

  - name: Install jdk
    package:
     name: default-jdk
     state: present

  - name: Copy chromedriver
    copy:
     src: /home/edureka/chromedriver
     dest: /home/edureka/

  - name: Install chromium browser
    package:
     name: chromium-browser
     state: present

  - name: Install chromium driver
    package:
     name: chromium-chromedriver
     state: present

  - name: Run update
    apt:
     update_cache: yes
